### ISSUE TITLE
Brake accelerate

### ISSUE THREAD

**Issue by hicham-barhoumi** [stancecoke/BMSBattery_S_controllers_firmware#11]
The brake does not brake, it accelerate !!!
When activating "Bypass PI control regen @lowspeed"
to reproduce the issue : 

- flash the rom with the configuration below
- start the bike
- use PAS
- Brake ....
![Capture2](https://user-images.githubusercontent.com/11330384/61595704-d548c300-abfa-11e9-8667-07fe0f7e62e7.PNG)

I think the code responsible for this bug is :
https://github.com/stancecoke/BMSBattery_S_controllers_firmware/blob/be04c47c79c7719e122302bb625030aadc4992fa/ACAsetPoint.c#L198-L202

PS: yes i think i m dead

**Comment by Xnyle** [comment]
This rather is an experimental setting for the BionX IHG3. To make it work we would have to make the motor constant variable editable.

Only "bug" is that it's not listed under experimental settings.

**Comment by Xnyle** [comment]
... to make it work for other motors. You can create a pull request if you'd like to change the configurator and/or the functionality itself
