### ISSUE TITLE
optionbytes write on linux. WriteOptionBytes.bat

### ISSUE THREAD

**Issue by fzellini** [stancecoke/BMSBattery_S_controllers_firmware#12]
The Java utility to create conf file and write option bytes calls windows bat file also on linux.
On linux i think it have to call something like "writeoptionbytes.sh".

Also, the included file optionbytes.hex works only with st programs on windows, does not work with stm8flash on linux, because it not include inverted bytes. 

So in order to program option bytes with stm8flash on linux the commands are:
```
echo "00 00 ff 20 DF 00 ff 00 ff 00 ff 00 ff 00 ff" | xxd -r -p > optionbytes-ok.bin
stm8flash -c stlinkv2 -p stm8s105?6 -s opt -w optionbytes-ok.bin
```

To clear option bytes to default you can use
```
stm8flash -c stlinkv2 -p stm8s105?6 -u
```

Anyway, thank you for the excellent work!

**Comment by Xnyle** [comment]
Thanks, great input! At some point I stopped bothering how to get this anyway hacked flashing stuff to work on linux ;-)

If I find the time I'll add the changes.

or feel free to submit a PR.
