### ISSUE TITLE
What works better & Known issues

### ISSUE THREAD

**Issue by AlexDaniel** [stancecoke/BMSBattery_S_controllers_firmware#15]
The README does not seem to advertise anything that works better when using this firmware. Now it doesn't really matter for me personally, as I'm looking for implementing some features specifically for myself, but I've seen this project for months and the readme kind of failed to convince me to try it earlier.

Also, IIRC there were some issues. One that was mentioned on the forums is that the controller gets hot when riding, or something like that?

**Comment by Xnyle** [comment]
Well that's even less of an issue than #16 is. So I'm closing it. Discussion should go into the forum.

**Comment by AlexDaniel** [comment]
@Xnyle hm. Any chance you misunderstood what I was trying to say? I'm talking about differences to the proprietary firmware that comes preinstalled, i.e. what are the benefits the open-source firmware provides. For example, customizable PAS levels would be something to mention.
