### ISSUE TITLE
app cant connect via bluetooth, crashes immeadiatly after commecting

### ISSUE THREAD

**Issue by yashyboi** [stancecoke/BMSBattery_S_controllers_firmware#19]
bluetooth doesnt work

**Comment by Xnyle** [comment]
Might be a user issue might be an app issue with newer anderoid versions.
Anyway, closing due to insufficient info provided.
If you seriously expect you problem to be addressed you might create a new issue providing logs / detailed system configuration etc. so maybe someone can help you.
