### ISSUE TITLE
Can you use the stock Bluetooth module with blu0sec?

### ISSUE THREAD

**Issue by yashyboi** [stancecoke/BMSBattery_S_controllers_firmware#20]
Not sure where to ask this so I'm asking here. I've got a Sony Xperia 1ii running Android 10. Whenever I use the blu0sec app and try to connect to the 18mosfet modded KT controller I have, I get a crash and a message saying "Blu0Sec" keeps crashing. The KT controller I bought came with a Bluetooth module, that plugs into a specific lead which is for Bluetooth modules, and there is a seperate header for displays. Do I need to get a hc-05 and use that to be able to connect to the app? I have tested the app on phones running Android 7, android 8, and two devices running Android 10. All of them experience the same issue. If more information is needed just let me know. Thank you so much.

**Comment by trimbles** [comment]
I have the same issue with the same controller and BT module, so i guess no is the answer......

**Comment by stancecoke** [comment]
for issues with the blue osec app, please open an issue at Xnyles repo:
https://github.com/Xnyle/bluosec-apk/
