### ISSUE TITLE
Speedometer problems

### ISSUE THREAD

**Issue by Techwizz-somboo** [stancecoke/BMSBattery_S_controllers_firmware#21]
Hey!
 I'm wondering if anyone can help me. On the BMSBattery project firmware, I use the KT48ZWSRLT-SJT02L controller, and my speedometer isn't even close to accurate. It's usually at something like 1-4. I checked to make sure it wasn't just showing the first digit because that's what it seemed at first but nope, that's not the case. It's also more random than I realized. I use the KT-LCD3 screen and wonder if I were to use the bluetooth app if it would fix it but I don't have one yet. Anyway anyone able to tell me a little bit? 
Thanks!

**Comment by stancecoke** [comment]
Proper settings for wheel circumference and gear ratio should solve this problem
