### ISSUE TITLE
Speed limit issue

### ISSUE THREAD

**Issue by hicham-barhoumi** [stancecoke/BMSBattery_S_controllers_firmware#7]
I have a KT36SVPR controller with LCD3 and i have a speed limit issue. The speed limit value is ignored if greater than 25Kph
Any idea please ?

**Comment by Xnyle** [comment]
Speedlimit def. works with values >25, not more info given, so no help.

Probably no help here anyway, make an effort to comprehensively describe how your setup is on the forum https://endless-sphere.com/forums/viewtopic.php?f=30&t=87870&start=3500
